name: testing dockerhub push
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: jlrivero/test_github_actions
      tag_with_ref: true
      tag_with_sha: true
      push: ${{ startsWith(github.ref, 'refs/tags/') }}
